# Generated by Django 6.1 on 2026-08-16 22:27

import uuid

import django.db.models.deletion
from django.db import migrations, models

import src.shared.infrastructure.persistence.django.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Question",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("text", models.CharField(max_length=200)),
                (
                    "response_type",
                    models.CharField(
                        choices=[
                            ("SINGLE", "SINGLE"),
                            ("MULTIPLE", "MULTIPLE"),
                            ("DEFINITION", "DEFINITION"),
                        ],
                        default="SINGLE",
                        max_length=20,
                    ),
                ),
                (
                    "tenant",
                    models.UUIDField(
                        db_column="tenant_id",
                        editable=False,
                        help_text="The tenant(uuid) this quiz is assigned to",
                    ),
                ),
                (
                    "tenant_user",
                    models.UUIDField(
                        db_column="tenant_user_id",
                        editable=False,
                        help_text="The tenant_user(uuid) that created this quiz",
                    ),
                ),
            ],
            options={
                "verbose_name": "Question",
                "verbose_name_plural": "Questions",
                "db_table": "question",
            },
        ),
        migrations.CreateModel(
            name="AnswerChoice",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("text", models.CharField(max_length=500)),
                ("is_correct", models.BooleanField(default=False)),
                (
                    "tenant",
                    models.UUIDField(
                        db_column="tenant_id",
                        editable=False,
                        help_text="The tenant UUID this answer belongs to.",
                    ),
                ),
                (
                    "tenant_user",
                    models.UUIDField(
                        db_column="tenant_user_id",
                        editable=False,
                        help_text="The tenant_user(uuid) that created this quiz",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="answers",
                        to="quiz.question",
                    ),
                ),
            ],
            options={
                "verbose_name": "Answer Choice",
                "verbose_name_plural": "Answer Choices",
                "db_table": "answer_choice",
            },
        ),
        migrations.CreateModel(
            name="Quiz",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        default=src.shared.infrastructure.persistence.django.models.nanoid_generator,
                        max_length=36,
                        unique=True,
                    ),
                ),
                (
                    "quiz_type",
                    models.CharField(
                        choices=[
                            ("FINAL_ASSESSMENT", "FINAL_ASSESSMENT"),
                            ("KNOWLEDGE_CHECK", "KNOWLEDGE_CHECK"),
                            ("PRACTICE", "PRACTICE"),
                        ],
                        default="PRACTICE",
                        max_length=30,
                    ),
                ),
                (
                    "configuration",
                    models.JSONField(default=dict, help_text="Quiz configuration."),
                ),
                (
                    "tenant",
                    models.UUIDField(
                        db_column="tenant_id",
                        editable=False,
                        help_text="The tenant(uuid) this quiz is assigned to",
                    ),
                ),
                (
                    "tenant_user",
                    models.UUIDField(
                        db_column="tenant_user_id",
                        editable=False,
                        help_text="The tenant_user(uuid) that created this quiz",
                    ),
                ),
            ],
            options={
                "verbose_name": "Quiz",
                "verbose_name_plural": "Quizzes",
                "db_table": "quiz",
                "indexes": [
                    models.Index(
                        condition=models.Q(("is_active", True), ("is_deleted", False)),
                        fields=["tenant"],
                        name="idx_quiz_tenant_active",
                    )
                ],
            },
        ),
        migrations.AddField(
            model_name="question",
            name="quiz",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="questions",
                to="quiz.quiz",
            ),
        ),
        migrations.CreateModel(
            name="QuizForm",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "user",
                    models.UUIDField(
                        db_column="user_id",
                        editable=False,
                        help_text="The user UUID that owns this quiz form.",
                    ),
                ),
                (
                    "tenant_user",
                    models.UUIDField(
                        blank=True,
                        db_column="tenant_user_id",
                        editable=False,
                        help_text="The optional tenant-user UUID associated with this form.",
                        null=True,
                    ),
                ),
                (
                    "correct_answers",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of correct responses in this form."
                    ),
                ),
                (
                    "wrong_answers",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Number of incorrect responses in this form.",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("NOT_STARTED", "NOT_STARTED"),
                            ("OPEN", "OPEN"),
                            ("COMPLETED", "COMPLETED"),
                            ("EXPIRED", "EXPIRED"),
                            ("CANCELLED", "CANCELLED"),
                        ],
                        default="NOT_STARTED",
                        max_length=50,
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "quiz_configuration_snapshot",
                    models.JSONField(
                        default=dict,
                        editable=False,
                        help_text="Immutable quiz configuration captured when the form started.",
                    ),
                ),
                (
                    "quiz",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="forms",
                        to="quiz.quiz",
                    ),
                ),
            ],
            options={
                "verbose_name": "Quiz Form",
                "verbose_name_plural": "Quiz Forms",
                "db_table": "quiz_form",
            },
        ),
        migrations.CreateModel(
            name="QuizQuestionResponse",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "user",
                    models.UUIDField(
                        db_column="user_id",
                        editable=False,
                        help_text="The user UUID that submitted this response.",
                    ),
                ),
                (
                    "tenant_user",
                    models.UUIDField(
                        blank=True,
                        db_column="tenant_user_id",
                        editable=False,
                        help_text="The optional tenant-user UUID associated with this form.",
                        null=True,
                    ),
                ),
                ("definition", models.TextField(blank=True, null=True)),
                (
                    "response_type",
                    models.CharField(
                        choices=[
                            ("SINGLE", "SINGLE"),
                            ("MULTIPLE", "MULTIPLE"),
                            ("DEFINITION", "DEFINITION"),
                        ],
                        editable=False,
                        help_text="Snapshot of Question.response_type at the time this response was recorded.",
                        max_length=20,
                    ),
                ),
                (
                    "answer_choice",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="user_responses",
                        to="quiz.answerchoice",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="user_responses",
                        to="quiz.question",
                    ),
                ),
                (
                    "quiz_form",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="responses",
                        to="quiz.quizform",
                    ),
                ),
            ],
            options={
                "verbose_name": "Quiz Question Response",
                "verbose_name_plural": "Quiz Question Responses",
                "db_table": "quiz_question_response",
            },
        ),
        migrations.CreateModel(
            name="QuizUserResult",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "user",
                    models.UUIDField(
                        db_column="user_id",
                        editable=False,
                        help_text="The user UUID associated with this result.",
                    ),
                ),
                (
                    "tenant_user",
                    models.UUIDField(
                        blank=True,
                        db_column="tenant_user_id",
                        editable=False,
                        help_text="The optional tenant-user UUID associated with this result.",
                        null=True,
                    ),
                ),
                (
                    "attempt_number",
                    models.PositiveIntegerField(
                        help_text="The number of the latest attempt represented by this result."
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("APPROVED", "APPROVED"), ("REJECTED", "REJECTED")],
                        default="REJECTED",
                        max_length=50,
                    ),
                ),
                (
                    "quiz",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="user_results",
                        to="quiz.quiz",
                    ),
                ),
                (
                    "quiz_form",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="current_result",
                        to="quiz.quizform",
                    ),
                ),
            ],
            options={
                "verbose_name": "Quiz User Result",
                "verbose_name_plural": "Quiz User Results",
                "db_table": "quiz_user_result",
            },
        ),
        migrations.CreateModel(
            name="QuizUserResultHistory",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "user",
                    models.UUIDField(
                        db_column="user_id",
                        editable=False,
                        help_text="The user UUID associated with this result.",
                    ),
                ),
                (
                    "tenant_user",
                    models.UUIDField(
                        blank=True,
                        db_column="tenant_user_id",
                        editable=False,
                        help_text="The optional tenant-user UUID associated with this result.",
                        null=True,
                    ),
                ),
                (
                    "attempt_number",
                    models.PositiveIntegerField(
                        help_text="The sequential number of the historical attempt."
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("APPROVED", "APPROVED"), ("REJECTED", "REJECTED")],
                        default="REJECTED",
                        max_length=50,
                    ),
                ),
                (
                    "quiz",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="result_history",
                        to="quiz.quiz",
                    ),
                ),
                (
                    "quiz_form",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="result_history",
                        to="quiz.quizform",
                    ),
                ),
            ],
            options={
                "verbose_name": "Quiz User Result History",
                "verbose_name_plural": "Quiz User Result Histories",
                "db_table": "quiz_user_result_history",
            },
        ),
        migrations.AddIndex(
            model_name="answerchoice",
            index=models.Index(
                condition=models.Q(("is_active", True), ("is_deleted", False)),
                fields=["question"],
                name="idx_answer_question_active",
            ),
        ),
        migrations.AddConstraint(
            model_name="answerchoice",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True), ("is_deleted", False)),
                fields=("tenant", "question", "text"),
                name="uq_answer_tenant_question_text",
            ),
        ),
        migrations.AddIndex(
            model_name="question",
            index=models.Index(
                condition=models.Q(("is_active", True), ("is_deleted", False)),
                fields=["quiz"],
                name="idx_question_quiz_active",
            ),
        ),
        migrations.AddConstraint(
            model_name="question",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True), ("is_deleted", False)),
                fields=("tenant", "quiz", "text", "response_type"),
                name="uq_question_tenant_quiz_text_response_type",
            ),
        ),
        migrations.AddIndex(
            model_name="quizform",
            index=models.Index(fields=["user", "quiz"], name="idx_quiz_form_user_quiz"),
        ),
        migrations.AddIndex(
            model_name="quizform",
            index=models.Index(
                fields=["tenant_user", "quiz"], name="idx_quiz_form_tenant_user_quiz"
            ),
        ),
        migrations.AddIndex(
            model_name="quizquestionresponse",
            index=models.Index(fields=["quiz_form"], name="idx_question_response_form"),
        ),
        migrations.AddConstraint(
            model_name="quizquestionresponse",
            constraint=models.UniqueConstraint(
                condition=models.Q(("response_type__in", ["SINGLE", "DEFINITION"])),
                fields=("quiz_form", "question"),
                name="uq_response_single_definition_one_row",
            ),
        ),
        migrations.AddConstraint(
            model_name="quizquestionresponse",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("answer_choice__isnull", False), ("response_type", "MULTIPLE")
                ),
                fields=("quiz_form", "question", "answer_choice"),
                name="uq_response_multiple_per_choice",
            ),
        ),
        migrations.AddConstraint(
            model_name="quizquestionresponse",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("answer_choice__isnull", False), ("definition__isnull", True)
                    ),
                    models.Q(
                        ("answer_choice__isnull", True), ("definition__isnull", False)
                    ),
                    _connector="OR",
                ),
                name="ck_response_exactly_one_answer",
            ),
        ),
        migrations.AddIndex(
            model_name="quizuserresult",
            index=models.Index(
                fields=["user", "quiz", "status"], name="idx_qur_user_quiz_status"
            ),
        ),
        migrations.AddIndex(
            model_name="quizuserresult",
            index=models.Index(
                fields=["tenant_user", "quiz", "status"],
                name="idx_qur_tenant_quiz_status",
            ),
        ),
        migrations.AddConstraint(
            model_name="quizuserresult",
            constraint=models.UniqueConstraint(
                condition=models.Q(("tenant_user__isnull", False)),
                fields=("user", "tenant_user", "quiz"),
                name="uq_quiz_user_result_user_tenant_user_quiz",
            ),
        ),
        migrations.AddConstraint(
            model_name="quizuserresult",
            constraint=models.UniqueConstraint(
                condition=models.Q(("tenant_user__isnull", True)),
                fields=("user", "quiz"),
                name="uq_quiz_user_result_user_quiz_no_tenant",
            ),
        ),
        migrations.AddIndex(
            model_name="quizuserresulthistory",
            index=models.Index(
                fields=["user", "quiz", "attempt_number"],
                name="idx_urh_user_quiz_attempt",
            ),
        ),
        migrations.AddIndex(
            model_name="quizuserresulthistory",
            index=models.Index(
                fields=["tenant_user", "quiz", "attempt_number"],
                name="idx_urh_tenant_quiz_attempt",
            ),
        ),
        migrations.AddConstraint(
            model_name="quizuserresulthistory",
            constraint=models.UniqueConstraint(
                condition=models.Q(("tenant_user__isnull", False)),
                fields=("user", "tenant_user", "quiz", "attempt_number"),
                name="uq_result_history_user_tenant_user_quiz_attempt",
            ),
        ),
        migrations.AddConstraint(
            model_name="quizuserresulthistory",
            constraint=models.UniqueConstraint(
                condition=models.Q(("tenant_user__isnull", True)),
                fields=("user", "quiz", "attempt_number"),
                name="uq_result_history_user_quiz_attempt_no_tenant",
            ),
        ),
    ]
