# Generated by Django 6.1 on 2026-08-16 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quizquestionresponse",
            name="response_type",
            field=models.CharField(
                choices=[
                    ("SINGLE", "SINGLE"),
                    ("MULTIPLE", "MULTIPLE"),
                    ("DEFINITION", "DEFINITION"),
                ],
                editable=False,
                help_text="Snapshot of Question.response_type when this response was recorded.",
                max_length=20,
            ),
        ),
    ]
