# Generated by Django 6.1 on 2026-08-25 01:00

from django.db import migrations, models


def _renumber(model, group_field, rows_updated_field="order"):
    """Assign a dense 1..N position per group, ordered by creation time.

    Returns the list to write; the caller does a single `bulk_update`, since
    saving row by row here would be one UPDATE per question on every existing
    quiz.
    """
    to_update = []
    current_group = object()
    position = 0

    for row in model.objects.order_by(group_field, "created_at", "id").iterator(
        chunk_size=1000
    ):
        group = getattr(row, group_field)
        if group != current_group:
            current_group = group
            position = 0
        position += 1
        setattr(row, rows_updated_field, position)
        to_update.append(row)

    return to_update


def renumber_existing_rows(apps, schema_editor):
    """Backfill positions for content created before ordering existed.

    Without this, every pre-existing row keeps the column default of 0 and
    the `("order", "created_at")` ordering degenerates to creation order —
    correct, but it would leave `order` lying about being dense and 1-based,
    which the create path guarantees for everything written afterwards.
    """
    Question = apps.get_model("quiz", "Question")
    AnswerChoice = apps.get_model("quiz", "AnswerChoice")

    questions = _renumber(Question, "quiz_id")
    if questions:
        Question.objects.bulk_update(questions, ["order"], batch_size=1000)

    choices = _renumber(AnswerChoice, "question_id")
    if choices:
        AnswerChoice.objects.bulk_update(choices, ["order"], batch_size=1000)


def reset_order(apps, schema_editor):
    """Reverse step: the column is dropped right after, so this only keeps
    the migration reversible without leaving a half-renumbered table if the
    rollback stops in between."""
    apps.get_model("quiz", "Question").objects.update(order=0)
    apps.get_model("quiz", "AnswerChoice").objects.update(order=0)


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0002_alter_quizquestionresponse_response_type"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="answerchoice",
            options={
                "ordering": ("order", "created_at"),
                "verbose_name": "Answer Choice",
                "verbose_name_plural": "Answer Choices",
            },
        ),
        migrations.AlterModelOptions(
            name="question",
            options={
                "ordering": ("order", "created_at"),
                "verbose_name": "Question",
                "verbose_name_plural": "Questions",
            },
        ),
        migrations.AddField(
            model_name="answerchoice",
            name="order",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Position of this choice within its question, starting at 1.",
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="order",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Position of this question within its quiz, starting at 1.",
            ),
        ),
        migrations.RunPython(renumber_existing_rows, reset_order),
        migrations.AddIndex(
            model_name="answerchoice",
            index=models.Index(
                fields=["question", "order"], name="idx_answer_question_order"
            ),
        ),
        migrations.AddIndex(
            model_name="question",
            index=models.Index(
                fields=["quiz", "order"], name="idx_question_quiz_order"
            ),
        ),
    ]
