# Generated by Django 6.1 on 2026-08-25 01:14

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0003_question_answer_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="answerchoice",
            name="deactivated_at",
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="question",
            name="deactivated_at",
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="quiz",
            name="deactivated_at",
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="quizuserresult",
            name="deactivated_at",
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="quizuserresulthistory",
            name="deactivated_at",
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.CreateModel(
            name="Area",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "deactivated_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                (
                    "tenant",
                    models.UUIDField(
                        db_column="tenant_id",
                        editable=False,
                        help_text="The tenant(uuid) this area belongs to",
                    ),
                ),
                (
                    "tenant_user",
                    models.UUIDField(
                        db_column="tenant_user_id",
                        editable=False,
                        help_text="The tenant_user(uuid) that created this area. Authorship only — an area belongs to its organization, not to its author, so this takes no part in the uniqueness constraint.",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        help_text="The root area this one belongs under, or empty if it is a root.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="children",
                        to="quiz.area",
                    ),
                ),
            ],
            options={
                "verbose_name": "Area",
                "verbose_name_plural": "Areas",
                "db_table": "area",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="QuizArea",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "tenant",
                    models.UUIDField(
                        db_column="tenant_id",
                        editable=False,
                        help_text="The tenant(uuid) this relation belongs to",
                    ),
                ),
                (
                    "tenant_user",
                    models.UUIDField(
                        db_column="tenant_user_id",
                        editable=False,
                        help_text="The tenant_user(uuid) that established this relation",
                    ),
                ),
                (
                    "area",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="quiz_areas",
                        to="quiz.area",
                    ),
                ),
                (
                    "quiz",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="quiz_areas",
                        to="quiz.quiz",
                    ),
                ),
            ],
            options={
                "verbose_name": "Quiz Area",
                "verbose_name_plural": "Quiz Areas",
                "db_table": "quiz_area",
            },
        ),
        migrations.AddIndex(
            model_name="area",
            index=models.Index(
                condition=models.Q(("is_active", True)),
                fields=["tenant"],
                name="idx_area_tenant_active",
            ),
        ),
        migrations.AddIndex(
            model_name="area",
            index=models.Index(fields=["parent"], name="idx_area_parent"),
        ),
        migrations.AddConstraint(
            model_name="area",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True)),
                fields=("tenant", "parent", "name"),
                name="uq_area_tenant_parent_name_active",
                nulls_distinct=False,
            ),
        ),
        migrations.AddConstraint(
            model_name="area",
            constraint=models.CheckConstraint(
                condition=models.Q(("parent", models.F("id")), _negated=True),
                name="ck_area_not_its_own_parent",
            ),
        ),
        migrations.AddIndex(
            model_name="quizarea",
            index=models.Index(fields=["area"], name="idx_quiz_area_area"),
        ),
        migrations.AddConstraint(
            model_name="quizarea",
            constraint=models.UniqueConstraint(
                fields=("quiz", "area"), name="uq_quiz_area_quiz_area"
            ),
        ),
    ]
