# Generated by Django 6.1 on 2026-08-16 22:28

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FailedEventMessage",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("channel_path", models.CharField(max_length=255)),
                ("handler_path", models.CharField(max_length=255)),
                ("resource_name", models.CharField(max_length=255)),
                (
                    "correlation_id",
                    models.UUIDField(
                        db_index=True,
                        help_text="Identifier used to correlate all events and operations belonging to the same request or business transaction.",
                    ),
                ),
                ("payload", models.JSONField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, null=True)),
                ("error_type", models.CharField(max_length=255)),
                ("error_message", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "PENDING"),
                            ("RESOLVED", "RESOLVED"),
                            ("ABANDONED", "ABANDONED"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("retry_count", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Failed event message",
                "verbose_name_plural": "Failed event messages",
                "db_table": "failed_event_message",
                "indexes": [
                    models.Index(
                        fields=["status", "created_at"], name="idx_failed_event_retry"
                    )
                ],
            },
        ),
    ]
