# Generated by Django 6.1 on 2026-08-16 23:10

import uuid

from django.db import migrations, models

import src.eventing.infrastructure.persistence.django.models.audit_log


class Migration(migrations.Migration):

    dependencies = [
        ("eventing", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "object_id",
                    models.UUIDField(
                        db_index=True, help_text="The ID of the audited record."
                    ),
                ),
                (
                    "object_repr",
                    models.TextField(
                        blank=True,
                        help_text="Human-readable snapshot of the audited record.",
                        null=True,
                    ),
                ),
                (
                    "user",
                    models.UUIDField(
                        blank=True,
                        db_column="user_id",
                        db_index=True,
                        editable=False,
                        help_text="The user UUID that performed the change, if any.",
                        null=True,
                    ),
                ),
                (
                    "tenant",
                    models.UUIDField(
                        blank=True,
                        db_column="tenant_id",
                        db_index=True,
                        editable=False,
                        help_text="The tenant UUID this change belongs to, if any.",
                        null=True,
                    ),
                ),
                (
                    "correlation_id",
                    models.UUIDField(
                        blank=True,
                        db_index=True,
                        editable=False,
                        help_text="Groups entries created by the same request or bulk operation.",
                        null=True,
                    ),
                ),
                (
                    "content_type",
                    models.CharField(
                        choices=[
                            ("TENANT", "TENANT"),
                            ("TENANT_USER", "TENANT_USER"),
                            ("USER", "USER"),
                            ("QUIZ", "QUIZ"),
                            ("QUESTION", "QUESTION"),
                            ("ANSWER_CHOICE", "ANSWER_CHOICE"),
                            ("QUIZ_FORM", "QUIZ_FORM"),
                            ("QUIZ_QUESTION_RESPONSE", "QUIZ_QUESTION_RESPONSE"),
                            ("QUIZ_USER_RESULT", "QUIZ_USER_RESULT"),
                            ("QUIZ_USER_RESULT_HISTORY", "QUIZ_USER_RESULT_HISTORY"),
                        ],
                        db_index=True,
                        editable=False,
                        help_text="Which model was changed.",
                        max_length=30,
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("API", "API"),
                            ("ADMIN", "ADMIN"),
                            ("COMMAND", "COMMAND"),
                            ("MIGRATION", "MIGRATION"),
                        ],
                        db_index=True,
                        editable=False,
                        help_text="Where the change originated.",
                        max_length=20,
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("ADDITION", "ADDITION"),
                            ("CHANGE", "CHANGE"),
                            ("DELETION", "DELETION"),
                        ],
                        db_index=True,
                        editable=False,
                        help_text="What kind of change happened.",
                        max_length=20,
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=src.eventing.infrastructure.persistence.django.models.audit_log.audit_log_metadata,
                        editable=False,
                        help_text="previous_state / current_state snapshots and descriptive messages.",
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Audit Log",
                "verbose_name_plural": "Audit Logs",
                "db_table": "audit_log",
                "indexes": [
                    models.Index(
                        fields=["tenant", "object_id", "content_type", "source_type"],
                        name="idx_audit_tenant_object_source",
                    ),
                    models.Index(
                        fields=[
                            "tenant",
                            "object_id",
                            "content_type",
                            "source_type",
                            "action_type",
                        ],
                        name="idx_audit_tenant_object_action",
                    ),
                    models.Index(
                        fields=["correlation_id"], name="idx_audit_correlation_id"
                    ),
                ],
            },
        ),
    ]
