# Generated by Django 6.1 on 2026-08-20 06:41

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eventing", "0002_auditlog"),
    ]

    operations = [
        migrations.CreateModel(
            name="IdempotencyKey",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("operation_id", models.UUIDField(editable=False, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("IN_PROGRESS", "IN_PROGRESS"),
                            ("SUCCEEDED", "SUCCEEDED"),
                            ("FAILED_TERMINAL", "FAILED_TERMINAL"),
                        ],
                        default="IN_PROGRESS",
                        max_length=20,
                    ),
                ),
                ("response_payload", models.JSONField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Idempotency key",
                "verbose_name_plural": "Idempotency keys",
                "db_table": "idempotency_key",
            },
        ),
    ]
