# Generated by Django 6.1 on 2026-08-16 22:28

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tenant",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "tenant_type",
                    models.CharField(
                        choices=[
                            ("COMPANY", "COMPANY"),
                            ("SCHOOL", "SCHOOL"),
                            ("UNIVERSITY", "UNIVERSITY"),
                        ],
                        db_column="type",
                        max_length=30,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(editable=False, max_length=255, unique=True)),
                ("address", models.CharField(blank=True, max_length=500)),
            ],
            options={
                "verbose_name": "Tenant",
                "verbose_name_plural": "Tenants",
                "db_table": "tenant",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant_type", "name"), name="uq_tenant_type_name"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="TenantUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("user", models.UUIDField(editable=False)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("ADMIN", "ADMIN"),
                            ("DIRECTOR", "DIRECTOR"),
                            ("COLLABORATOR", "COLLABORATOR"),
                            ("GUEST", "GUEST"),
                        ],
                        default="COLLABORATOR",
                        max_length=30,
                    ),
                ),
                (
                    "activated_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "deactivated_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="user_tenants",
                        to="tenant.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tenant User",
                "verbose_name_plural": "Tenant Users",
                "db_table": "tenant_user",
            },
        ),
    ]
