"""
Django settings for main project.

Generated by 'django-admin startproject' using Django 6.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

from pathlib import Path

from django.conf.global_settings import MIGRATION_MODULES

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-6rv%k&1_bzfz1%@eno4#sp96kxxc)h-9iv#=ay=q^y=029($vk"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "src.quiz",
    "src.tenant",
    "src.identity",
    "src.eventing",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "main.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "main.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

import dj_database_url  # noqa: E402

from main.project_settings import settings  # noqa: E402

AUTH_USER_MODEL = "identity.MyUser"

DATABASES = {
    "default": dj_database_url.parse(
        settings.DATABASE.url.get_secret_value(),
        conn_max_age=settings.DATABASE.conn_max_age,
    )
}

MIGRATION_MODULES: dict[str, str] = {
    "identity": "src.identity.infrastructure.persistence.django.migrations",
    "quiz": "src.quiz.infrastructure.persistence.django.migrations",
    "tenant": "src.tenant.infrastructure.persistence.django.migrations",
    "eventing": "src.eventing.infrastructure.persistence.django.migrations",
}

# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = "static/"


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

MAILERS = {
    "default": {
        "BACKEND": "django.core.mail.backends.console.EmailBackend",
    },
}


# Logging
# structlog wired to stdlib logging — see src/shared/infrastructure/logging.
# Every log line (structlog-originated or not, e.g. Django's own) is rendered
# consistently: human-readable in DEBUG, line-delimited JSON otherwise (ready
# to ship to a log aggregator once the Grafana/Prometheus stack is wired up).

from src.shared.infrastructure.logging import configure_logging  # noqa: E402

configure_logging(json_logs=not DEBUG)
