# Generated by Django 6.1 on 2026-08-18 23:05

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        # A plain AlterField can't change a bigint PK column to uuid in
        # place (Postgres has no bigint->uuid cast). Drop and re-add
        # instead — safe because no environment has real UserTenant data
        # yet (this is a pre-launch fix, not a production migration).
        migrations.RemoveField(
            model_name="usertenant",
            name="id",
        ),
        migrations.AddField(
            model_name="usertenant",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
