# Generated by Django 6.1 on 2026-08-25 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0002_alter_usertenant_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="deactivated_at",
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
